server:
  port: 7001
eureka:
  instance:
    #hostname: localhost #eureka单点服务端的实例名称
    hostname: eureka7001.com #需要做主机域名映射，因为对外暴露的集群名不能都相同，本地hosts文件配置了127.0.0.1  eureka7001.com
  client:
    registerWithEureka: false #false表示不向注册中心注册自己
    fetchRegistry: false #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
    serviceUrl:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群配置7001牵手其它所有非7001的服务端
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
